apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert -f ..\docker-compose.yml -f ..\docker-compose.openshift.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: data-ws
  name: data-ws
spec:
  ports:
  - name: "8480"
    port: 8480
    targetPort: 8080
  selector:
    io.kompose.service: data-ws
status:
  loadBalancer: {}
