apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert -f ..\docker-compose.yml -f ..\docker-compose.openshift.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kie-server
  name: kie-server
spec:
  ports:
  - name: "8180"
    port: 8180
    targetPort: 8080
  selector:
    io.kompose.service: kie-server
status:
  loadBalancer: {}
