apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert -f ..\docker-compose.yml -f ..\docker-compose.openshift.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresql-kie
  name: postgresql-kie
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgresql-kie
    spec:
      containers:
      - env:
        - name: POSTGRESQL_DATABASE
          value: kieserver
        - name: POSTGRESQL_PASSWORD
          value: K1eS3rv3rUserPass
        - name: POSTGRESQL_USER
          value: kieserver
        image: development.corvex.hu:5020/tm-postgresql-kie:1
        name: postgresql-kie
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: kie-pgdata
      restartPolicy: Always
      volumes:
      - name: kie-pgdata
        persistentVolumeClaim:
          claimName: kie-pgdata
status: {}
