apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert -f ..\docker-compose.yml -f ..\docker-compose.openshift.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: workflow-api
  name: workflow-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: workflow-api
    spec:
      containers:
      - env:
        - name: JDK_ENV_VARS
          value: -Dkie.rest.host=kie-server -Dkie.rest.port=8180
        image: development.corvex.hu:5020/cvx-workflow-api:8
        name: workflow-api
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
